### ISSUE TITLE
cannot build with last rtabmap version master

### ISSUE THREAD

**Issue by FPSychotic** [introlab/rtabmap#792]
i could with 20.14 and 20.15 without issues

`[ 60%] Generating ui_exportCloudsDialog.h
[ 61%] Generating ui_exportDialog.h
[ 61%] Generating ui_loopClosureViewer.h
[ 61%] Generating ui_mainWindow.h
[ 61%] Generating ui_postProcessingDialog.h
Scanning dependencies of target rtabmap_gui
[ 62%] Building CXX object guilib/src/CMakeFiles/rtabmap_gui.dir/MainWindow.cpp.o
[ 62%] Linking CXX executable ../../bin/rtabmap-camera
/usr/bin/ld: CMakeFiles/camera.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x200): undefined reference to `ULogger::kDefaultLogFileName'
/usr/bin/ld: main.cpp:(.text.startup+0x220): undefined reference to `ULogger::kDefaultLogFileName'
/usr/bin/ld: main.cpp:(.text.startup+0x24c): undefined reference to `ULogger::setType(ULogger::Type, std::string const&, bool)'
/usr/bin/ld: main.cpp:(.text.startup+0x2cc): undefined reference to `uStr2Float(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x3ac): undefined reference to `UFile::exists(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x3c4): undefined reference to `UFile::getExtension(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x4e0): undefined reference to `UDirectory::getDir(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x4f0): undefined reference to `UFile::getName(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x61c): undefined reference to `UDirectory::exists(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x798): undefined reference to `cv::namedWindow(std::string const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x800): undefined reference to `cv::destroyWindow(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x860): undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uNumber2Str(float)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZI>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `g2o::Factory::registerType(std::string const&, g2o::AbstractHyperGraphElementCreator*)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uToUpperCase(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::Factor::printKeys(std::string const&, std::function<std::string (unsigned long)> const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointNormal>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZ>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `g2o::Factory::unregisterType(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UDirectory::makeDir(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDWriter::resetLockingPermissions(std::string const&, boost::interprocess::file_lock&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UDirectory::getNextFileName()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::FileStorage::FileStorage(std::string const&, int, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UFile::length(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::Unit3::print(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UDirectory::separator()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::FileStorage::writeRaw(std::string const&, void const*, unsigned long)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::FileNode::string() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uNumber2Str(double)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZRGBNormal>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::error(int, std::string const&, char const*, char const*, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::_multirobotKeyFormatter(unsigned long)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::ONIGrabber::ONIGrabber(std::string const&, bool, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::FileNodeIterator::readRaw(std::string const&, void*, unsigned long)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZRGBNormal>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uNumber2Str(int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDWriter::writeBinary(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `dai::Device::getOutputQueue(std::string const&, unsigned int, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::NoiseModelFactor::print(std::string const&, std::function<std::string (unsigned long)> const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::write(cv::FileStorage&, std::string const&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UVariant::toStr(bool*) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDReader::read(std::string const&, pcl::PCLPointCloud2&, Eigen::Matrix<float, 4, 1, 0, 4, 1>&, Eigen::Quaternion<float, 0>&, int&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `octomap::AbstractOccupancyOcTree::writeBinary(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::Rot2::print(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uReplaceChar(std::string const&, char, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::_defaultKeyFormatter(unsigned long)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uReplaceChar(std::string const&, char, char)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UDirectory::UDirectory(std::string const&, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uHex2Str(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::io::saveVTKFile(std::string const&, pcl::PCLPointCloud2 const&, unsigned int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uNumber2Str(unsigned int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZI>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::demangle(char const*)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::VideoCapture::open(std::string const&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZRGB>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::getBuildInformation()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `ceres::Solver::Summary::FullReport() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `dai::DeviceBase::getMxId()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::internal::WriteStructContext::WriteStructContext(cv::FileStorage&, std::string const&, int, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PLYWriter::writeASCII(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::OpenNIGrabber::OpenNIGrabber(std::string const&, pcl::OpenNIGrabber::Mode const&, pcl::OpenNIGrabber::Mode const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uStr2Bool(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::Algorithm::getDefaultName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDWriter::writeASCII(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UVariant::UVariant(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uFormat(char const*, ...)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::print(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `dai::node::XLinkOut::setStreamName(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::Pose3::print(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZINormal>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::NonlinearOptimizerParams::print(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PLYWriter::writeBinary(std::string const&, pcl::PCLPointCloud2 const&, Eigen::Matrix<float, 4, 1, 0, 4, 1> const&, Eigen::Quaternion<float, 0> const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `ULogger::registerCurrentThread(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::Algorithm::save(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZ>::Search(std::string const&, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDReader::read(std::string const&, pcl::PCLPointCloud2&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UFile::rename(std::string const&, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `gtsam::Pose2::print(std::string const&) const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `g2o::Cache::CacheKey::CacheKey(std::string const&, std::vector<g2o::Parameter*, std::allocator<g2o::Parameter*> > const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZRGB>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::operator<<(cv::FileStorage&, std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointNormal>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `dai::DeviceInfo::getMxId() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uStr2Int(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `g2o::writeCCSMatrix(std::string const&, int, int, int const*, int const*, double const*, bool)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PCDWriter::setLockingPermissions(std::string const&, boost::interprocess::file_lock&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uStr2Double(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UFile::erase(std::string const&)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::PLYReader::read(std::string const&, pcl::PCLPointCloud2&, Eigen::Matrix<float, 4, 1, 0, 4, 1>&, Eigen::Quaternion<float, 0>&, int&, int)'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `pcl::search::Search<pcl::PointXYZINormal>::getName() const'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `UDirectory::homeDir()'
/usr/bin/ld: ../../bin/librtabmap_core.so.0.20.16: undefined reference to `uBool2Str(bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/Camera/CMakeFiles/camera.dir/build.make:426: bin/rtabmap-camera] Error 1
make[1]: *** [CMakeFiles/Makefile2:3279: tools/Camera/CMakeFiles/camera.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 62%] Building CXX object guilib/src/CMakeFiles/rtabmap_gui.dir/PreferencesDialog.cpp.o
[ 63%] Linking CXX executable ../../bin/rtabmap-stereoEval
/usr/bin/ld: CMakeFiles/stereoEval.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x8): undefined reference to `ULogger::kDefaultLogFileName'
/usr/bin/ld: main.cpp:(.text.startup+0x20): undefined reference to `ULogger::kDefaultLogFileName'
/usr/bin/ld: main.cpp:(.text.startup+0x64): undefined reference to `ULogger::setType(ULogger::Type, std::string const&, bool)'
/usr/bin/ld: main.cpp:(.text.startup+0x490): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x4d0): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x520): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x7a4): undefined reference to `uReplaceChar(std::string const&, char, std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x800): undefined reference to `uReplaceChar(std::string const&, char, std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0xa98): undefined reference to `uStr2Double(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0xb00): undefined reference to `uStr2Double(std::string const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x14e0): undefined reference to `cv::namedW`

**Comment by FPSychotic** [comment]
I could compile 20.14 again, but now rtabmap_ros doesnt install with it (something related with gtam,maybe a new udate from ppa?). I removed any file, resourced etc. nothing works, everything started having 0.20.14 working in ros1 noetic 20.04 and 0.20.15 in foxy, git pull, and everything went broken.

**Comment by FPSychotic** [comment]
the problem was that with open3d , wont compile with it

**Comment by matlabbe** [comment]
`WITH_OPEN3D` is OFF by default. Do I understand with your last comment that it is fine with `-DWITH_OPEN3D=OFF` but not `-DWITH_OPEN3D=ON` ?

**Comment by FPSychotic** [comment]
Yes it works with open3d off. I have it compiled in a ARM64 ketdom Xavier so it is experimental.
Maybe is that

**Comment by matlabbe** [comment]
Open3D support inside rtabmap is quite experimental too, it is why it is disabled by default. I'll close this issue for the original error.
