### ISSUE TITLE
iOS-APP: Errors with XCode 16.3 - Clang 17

### ISSUE THREAD

**Issue by zeitlerv** [introlab/rtabmap#1482]
After updating to Xcode 16.3 (see [Xcode 16.3 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16_3-release-notes)), our iOS build fails with the following errors involving Boost. It seems that Boost’s older code has invalid enum values for Clang’s stricter checks, and Eigen triggers a separate error during compilation. Attempting to upgrade Boost to 1.86 introduced another problem (missing signals/signals2 references).

Errors when trying to start the app:

`
Xcode build done.                                           62,4s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'udt_builtin_mixture_enum'
/Users/UserName/StudioProjects/rtabmap/app/ios/Libraries/include/boost/mpl/aux_/integral_wrapper.hpp:72:30
Error (Xcode): integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'int_float_mixture_enum'
/Users/UserName/StudioProjects/rtabmap/app/ios/Libraries/include/boost/mpl/aux_/integral_wrapper.hpp:72:30
Error (Xcode): integer value -1 is outside the valid range of values [0, 3] for the enumeration type 'sign_mixture_enum'
/Users/UserName/StudioProjects/rtabmap/app/ios/Libraries/include/boost/mpl/aux_/integral_wrapper.hpp:72:30
Error (Xcode): integer value 4 is outside the valid range of values [0, 3] for the enumeration type 'sign_mixture_enum'
/Users/UserName/StudioProjects/rtabmap/app/ios/Libraries/include/boost/mpl/aux_/integral_wrapper.hpp:71:30`

Similar Issue: https://github.com/boostorg/boost/issues/907

When trying to run install_deps.sh:

`[ 53%] Building CXX object Filters/Statistics/CMakeFiles/vtkFiltersStatistics.dir/vtkMultiCorrelativeStatistics.cxx.o
[ 53%] Building CXX object Filters/Statistics/CMakeFiles/vtkFiltersStatistics.dir/vtkOrderStatistics.cxx.o
[ 53%] Building CXX object Filters/Statistics/CMakeFiles/vtkFiltersStatistics.dir/vtkPCAStatistics.cxx.o
In file included from /Users/UserName/StudioProjects/rtabmap/app/ios/RTABMapApp/Libraries/VTK/Filters/Statistics/vtkPCAStatistics.cxx:19:
In file included from /Users/UserName/StudioProjects/rtabmap/app/ios/RTABMapApp/Libraries/VTK/ThirdParty/eigen/vtkeigen/eigen/Dense:1:
In file included from /Users/UserName/StudioProjects/rtabmap/app/ios/RTABMapApp/Libraries/VTK/ThirdParty/eigen/vtkeigen/eigen/Core:469:
/Users/UserName/StudioProjects/rtabmap/app/ios/RTABMapApp/Libraries/VTK/ThirdParty/eigen/vtkeigen/eigen/src/Core/Transpositions.h:387:87: error: 
no member named 'derived' in 'Transpose<TranspositionsBase<type-parameter-0-0>>'
  387 |     return Product<OtherDerived, Transpose, AliasFreeProduct>(matrix.derived(), trt.derived());
                                                             ~~~~~ ^
1 error generated.
make[5]: *** [Filters/Statistics/CMakeFiles/vtkFiltersStatistics.dir/vtkPCAStatistics.cxx.o] Error 1
make[4]: *** [Filters/Statistics/CMakeFiles/vtkFiltersStatistics.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [CMakeExternals/Prefix/vtk-ios-device-arm64/src/vtk-ios-device-arm64-stamp/vtk-ios-device-arm64-build] Error 2
make[1]: *** [CMakeFiles/vtk-ios-device-arm64.dir/all] Error 2
make: *** [all] Error 2`

**Comment by matlabbe** [comment]
Commit above made it work on XCode 16.3. Closing.
